# -*- coding: utf-8 -*-
"""Weather analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/weather-analysis-8fa224a7-50cf-4eaf-a8ea-92d679b852a8.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240412/auto/storage/goog4_request%26X-Goog-Date%3D20240412T155107Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D10700f4ee511ff81e4c14cdc15efe93b9bc24efb89a58d5da672b11a622f26383b2a332c387ad7a64a4bfd99201b650d0c2ccb7e8cc6e41dc71f3c7edf13092f4e38aa267dc624fa5eb8a54d8ff53db6145f2c019b40b1a8492f856db163d25d4a1fb75d99b34630af1c97649009520caaf3b021f68f8e137c1539f8af267d87df2b5700bbbd15bb7148a659542a5e7efabed40056ad6257f17b170782aa508800b070020dd06f2484a904c412891c5a189e3a372910e4d0b766a4ec7a4743f588222609544584fd65e0349fbe157bdb4005033be9c43183e6b148b796b6a747ef0373c94ae107f0f9e7d31f5f47712a77501c4ac149012fede0c7c339153d5f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/input/weather-prediction/seattle-weather.csv")
data

data.info()

data.columns.to_list()

data.describe()

continuous_cols = data.select_dtypes(include='number').columns
correlation_matrix = data[continuous_cols].corr()
plt.figure(figsize=(6,4)) # size
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.show()